# flask
локально все нормально запустилось, 
при создании образа не запускалось были проблемы с модулем 
AttributeError: module 'wtforms.validators' has no attribute 'required'
решилось устновкой с образом python 2.7
